CREATE TABLE IF NOT EXISTS validation.reporting_validation_runs (
    reporting_validation_run_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analytics_build_run_id       bigint NOT NULL,
    ingestion_batch_id           bigint NOT NULL,
    status                       text NOT NULL DEFAULT 'running',
    expected_check_count         integer NOT NULL,
    completed_check_count        integer NOT NULL DEFAULT 0,
    passed_check_count           integer NOT NULL DEFAULT 0,
    failed_check_count           integer NOT NULL DEFAULT 0,
    total_violations             bigint NOT NULL DEFAULT 0,
    started_at                   timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at                 timestamptz,
    error_message                text,

    CONSTRAINT reporting_validation_runs_build_fk
        FOREIGN KEY (analytics_build_run_id)
        REFERENCES analytics.build_runs(analytics_build_run_id)
        ON DELETE RESTRICT,

    CONSTRAINT reporting_validation_runs_status_chk
        CHECK (status IN ('running', 'succeeded', 'failed')),

    CONSTRAINT reporting_validation_runs_expected_chk
        CHECK (expected_check_count > 0),

    CONSTRAINT reporting_validation_runs_counts_chk
        CHECK (
            completed_check_count >= 0
            AND passed_check_count >= 0
            AND failed_check_count >= 0
            AND total_violations >= 0
            AND completed_check_count <= expected_check_count
            AND completed_check_count =
                passed_check_count + failed_check_count
        ),

    CONSTRAINT reporting_validation_runs_completion_chk
        CHECK (
            (
                status = 'running'
                AND completed_at IS NULL
            )
            OR
            (
                status IN ('succeeded', 'failed')
                AND completed_at IS NOT NULL
            )
        ),

    CONSTRAINT reporting_validation_runs_success_chk
        CHECK (
            status <> 'succeeded'
            OR (
                completed_check_count = expected_check_count
                AND failed_check_count = 0
                AND total_violations = 0
            )
        )
);


CREATE UNIQUE INDEX IF NOT EXISTS
    uq_reporting_validation_successful_build
ON validation.reporting_validation_runs (
    analytics_build_run_id
)
WHERE status = 'succeeded';


CREATE INDEX IF NOT EXISTS
    ix_reporting_validation_runs_status
ON validation.reporting_validation_runs (
    status
);


CREATE TABLE IF NOT EXISTS validation.reporting_validation_results (
    reporting_validation_result_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporting_validation_run_id    bigint NOT NULL,
    check_category                  text NOT NULL,
    check_name                      text NOT NULL,
    passed                          boolean NOT NULL,
    violation_count                 bigint NOT NULL,
    observed_value                  text,
    expected_value                  text,
    detail                          text,
    checked_at                      timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT reporting_validation_results_run_fk
        FOREIGN KEY (reporting_validation_run_id)
        REFERENCES validation.reporting_validation_runs(reporting_validation_run_id)
        ON DELETE RESTRICT,

    CONSTRAINT reporting_validation_results_violation_chk
        CHECK (violation_count >= 0),

    CONSTRAINT reporting_validation_results_pass_chk
        CHECK (
            (passed AND violation_count = 0)
            OR
            (NOT passed AND violation_count > 0)
        ),

    CONSTRAINT reporting_validation_results_check_uk
        UNIQUE (
            reporting_validation_run_id,
            check_name
        )
);


COMMENT ON TABLE validation.reporting_validation_runs IS
    'Persisted validation runs for the Pulse reporting semantic layer, keyed to a successful analytics build.';

COMMENT ON TABLE validation.reporting_validation_results IS
    'Individual reporting semantic-layer validation results with persisted pass/fail and violation counts.';


CREATE OR REPLACE FUNCTION validation.record_reporting_validation_result(
    p_reporting_validation_run_id bigint,
    p_check_category              text,
    p_check_name                  text,
    p_passed                      boolean,
    p_violation_count             bigint,
    p_observed_value              text,
    p_expected_value              text,
    p_detail                      text
)
RETURNS void
LANGUAGE sql
AS $$
    INSERT INTO validation.reporting_validation_results (
        reporting_validation_run_id,
        check_category,
        check_name,
        passed,
        violation_count,
        observed_value,
        expected_value,
        detail
    )
    VALUES (
        p_reporting_validation_run_id,
        p_check_category,
        p_check_name,
        p_passed,
        p_violation_count,
        p_observed_value,
        p_expected_value,
        p_detail
    )
    ON CONFLICT (
        reporting_validation_run_id,
        check_name
    )
    DO UPDATE
    SET
        check_category = EXCLUDED.check_category,
        passed = EXCLUDED.passed,
        violation_count = EXCLUDED.violation_count,
        observed_value = EXCLUDED.observed_value,
        expected_value = EXCLUDED.expected_value,
        detail = EXCLUDED.detail,
        checked_at = clock_timestamp();
$$;


CREATE OR REPLACE FUNCTION validation.validate_reporting_build(
    p_analytics_build_run_id bigint
)
RETURNS TABLE (
    result_reporting_validation_run_id bigint,
    result_status                      text,
    result_already_validated           boolean,
    result_expected_check_count        integer,
    result_completed_check_count       integer,
    result_passed_check_count          integer,
    result_failed_check_count          integer,
    result_total_violations            bigint,
    result_error_message               text
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_expected_check_count constant integer := 31;

    v_run_id                bigint;
    v_existing_run_id       bigint;
    v_ingestion_batch_id    bigint;
    v_build_status          text;

    v_completed             integer := 0;
    v_passed                integer := 0;
    v_failed                integer := 0;
    v_total_violations      bigint := 0;
    v_final_status          text;
    v_error                 text;

    v_metric_total          bigint;
    v_metric_supported      bigint;
    v_metric_deferred       bigint;
    v_metric_unsupported    bigint;

    v_dim_date_rows         bigint;
    v_source_installations  bigint;
    v_source_signups        bigint;

    v_source_onboarding_started   bigint;
    v_source_onboarding_completed bigint;
    v_source_feature_events       bigint;

    v_lifecycle_rows        bigint;
    v_lifecycle_unique      bigint;

    v_daily_product_rows    bigint;
    v_rpt_installations     bigint;
    v_rpt_signups           bigint;
    v_rpt_onboarding_started   bigint;
    v_rpt_onboarding_completed bigint;

    v_source_payment_attempts  bigint;
    v_source_payment_successes bigint;
    v_source_payment_failures  bigint;
    v_source_success_revenue   numeric;

    v_daily_revenue_rows       bigint;
    v_rpt_payment_attempts     bigint;
    v_rpt_payment_successes    bigint;
    v_rpt_payment_failures     bigint;
    v_rpt_success_revenue      numeric;

    v_source_marketing_rows    bigint;
    v_source_marketing_spend   numeric;

    v_rpt_marketing_rows       bigint;
    v_rpt_marketing_spend      numeric;
    v_rpt_acquisition_installs bigint;
    v_rpt_acquisition_signups  bigint;

    v_source_trial_rows        bigint;
    v_rpt_trial_rows           bigint;

    v_source_paid_rows         bigint;
    v_rpt_paid_retention_rows  bigint;

    v_source_experiment_rows       bigint;
    v_source_experiment_exposures  bigint;

    v_rpt_experiment_rows          bigint;
    v_rpt_experiment_unique        bigint;
    v_rpt_experiment_exposures     bigint;

    v_summary_assignments          bigint;
    v_summary_exposures            bigint;

    v_rate_violations              bigint;
    v_retention_violations         bigint;
BEGIN
    PERFORM pg_advisory_xact_lock(
        hashtextextended(
            'reporting-validation:' ||
            p_analytics_build_run_id::text,
            0
        )
    );

    SELECT
        ingestion_batch_id,
        status
    INTO
        v_ingestion_batch_id,
        v_build_status
    FROM analytics.build_runs
    WHERE analytics_build_run_id =
          p_analytics_build_run_id
    FOR SHARE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'analytics build run % does not exist',
            p_analytics_build_run_id;
    END IF;

    IF v_build_status <> 'succeeded' THEN
        RAISE EXCEPTION
            'analytics build run % is not succeeded: %',
            p_analytics_build_run_id,
            v_build_status;
    END IF;

    SELECT reporting_validation_run_id
    INTO v_existing_run_id
    FROM validation.reporting_validation_runs
    WHERE analytics_build_run_id =
          p_analytics_build_run_id
      AND status = 'succeeded'
    ORDER BY reporting_validation_run_id
    LIMIT 1;

    IF v_existing_run_id IS NOT NULL THEN
        RETURN QUERY
        SELECT
            r.reporting_validation_run_id,
            r.status,
            true,
            r.expected_check_count,
            r.completed_check_count,
            r.passed_check_count,
            r.failed_check_count,
            r.total_violations,
            r.error_message
        FROM validation.reporting_validation_runs r
        WHERE r.reporting_validation_run_id =
              v_existing_run_id;

        RETURN;
    END IF;

    INSERT INTO validation.reporting_validation_runs (
        analytics_build_run_id,
        ingestion_batch_id,
        status,
        expected_check_count
    )
    VALUES (
        p_analytics_build_run_id,
        v_ingestion_batch_id,
        'running',
        v_expected_check_count
    )
    RETURNING reporting_validation_run_id
    INTO v_run_id;

    BEGIN
        -- ----------------------------------------------------
        -- Metric contract profile
        -- ----------------------------------------------------

        SELECT
            COUNT(*)::bigint,
            COUNT(*) FILTER (
                WHERE support_status = 'supported'
            )::bigint,
            COUNT(*) FILTER (
                WHERE support_status = 'deferred'
            )::bigint,
            COUNT(*) FILTER (
                WHERE support_status = 'unsupported'
            )::bigint
        INTO
            v_metric_total,
            v_metric_supported,
            v_metric_deferred,
            v_metric_unsupported
        FROM reporting.metric_definitions;


        -- ----------------------------------------------------
        -- Core source counts
        -- ----------------------------------------------------

        SELECT COUNT(*)::bigint
        INTO v_dim_date_rows
        FROM analytics.dim_date;

        SELECT COUNT(*)::bigint
        INTO v_source_installations
        FROM analytics.dim_installation
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;

        SELECT COUNT(*)::bigint
        INTO v_source_signups
        FROM analytics.dim_user
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;

        SELECT
            COUNT(*) FILTER (
                WHERE event_name = 'onboarding_started'
            )::bigint,

            COUNT(*) FILTER (
                WHERE event_name = 'onboarding_completed'
            )::bigint,

            COUNT(*) FILTER (
                WHERE event_name = 'feature_used'
            )::bigint

        INTO
            v_source_onboarding_started,
            v_source_onboarding_completed,
            v_source_feature_events

        FROM analytics.fact_product_event
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        -- ----------------------------------------------------
        -- Installation lifecycle
        -- ----------------------------------------------------

        SELECT
            COUNT(*)::bigint,
            COUNT(DISTINCT installation_key)::bigint
        INTO
            v_lifecycle_rows,
            v_lifecycle_unique
        FROM reporting.vw_installation_lifecycle
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        -- ----------------------------------------------------
        -- Daily product
        -- ----------------------------------------------------

        SELECT
            COUNT(*)::bigint,
            COALESCE(SUM(installation_count), 0)::bigint,
            COALESCE(SUM(signup_count), 0)::bigint,
            COALESCE(SUM(onboarding_started_count), 0)::bigint,
            COALESCE(SUM(onboarding_completed_count), 0)::bigint
        INTO
            v_daily_product_rows,
            v_rpt_installations,
            v_rpt_signups,
            v_rpt_onboarding_started,
            v_rpt_onboarding_completed
        FROM reporting.vw_daily_product_kpis
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        -- ----------------------------------------------------
        -- Payment / revenue source
        -- ----------------------------------------------------

        SELECT
            COUNT(*)::bigint,

            COUNT(*) FILTER (
                WHERE payment_status = 'succeeded'
            )::bigint,

            COUNT(*) FILTER (
                WHERE payment_status = 'failed'
            )::bigint,

            COALESCE(
                SUM(amount_gbp) FILTER (
                    WHERE payment_status = 'succeeded'
                ),
                0
            )::numeric

        INTO
            v_source_payment_attempts,
            v_source_payment_successes,
            v_source_payment_failures,
            v_source_success_revenue

        FROM analytics.fact_subscription_transaction
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        SELECT
            COUNT(*)::bigint,
            COALESCE(SUM(payment_attempt_count), 0)::bigint,
            COALESCE(SUM(successful_payment_count), 0)::bigint,
            COALESCE(SUM(failed_payment_count), 0)::bigint,
            COALESCE(
                SUM(successful_payment_revenue_gbp),
                0
            )::numeric
        INTO
            v_daily_revenue_rows,
            v_rpt_payment_attempts,
            v_rpt_payment_successes,
            v_rpt_payment_failures,
            v_rpt_success_revenue
        FROM reporting.vw_daily_subscription_revenue
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        -- ----------------------------------------------------
        -- Marketing / acquisition
        -- ----------------------------------------------------

        SELECT
            COUNT(*)::bigint,
            COALESCE(SUM(spend), 0)::numeric
        INTO
            v_source_marketing_rows,
            v_source_marketing_spend
        FROM analytics.fact_marketing_spend
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        SELECT
            COUNT(*)::bigint,
            COALESCE(SUM(marketing_spend_gbp), 0)::numeric,
            COALESCE(SUM(installation_count), 0)::bigint,
            COALESCE(SUM(installations_with_signup), 0)::bigint
        INTO
            v_rpt_marketing_rows,
            v_rpt_marketing_spend,
            v_rpt_acquisition_installs,
            v_rpt_acquisition_signups
        FROM reporting.vw_weekly_acquisition_performance
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        -- ----------------------------------------------------
        -- Trial / retention
        -- ----------------------------------------------------

        SELECT COUNT(*)::bigint
        INTO v_source_trial_rows
        FROM analytics.fact_subscription
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        SELECT
            COALESCE(SUM(trial_count), 0)::bigint
        INTO v_rpt_trial_rows
        FROM reporting.vw_trial_conversion_cohorts
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        SELECT COUNT(*)::bigint
        INTO v_source_paid_rows
        FROM analytics.fact_subscription
        WHERE analytics_build_run_id =
              p_analytics_build_run_id
          AND subscription_started_at IS NOT NULL;


        SELECT COUNT(*)::bigint
        INTO v_rpt_paid_retention_rows
        FROM reporting.vw_paid_subscription_retention_base
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        -- ----------------------------------------------------
        -- Experiment outputs
        -- ----------------------------------------------------

        SELECT
            COUNT(*)::bigint,

            COUNT(*) FILTER (
                WHERE exposed_at IS NOT NULL
            )::bigint
        INTO
            v_source_experiment_rows,
            v_source_experiment_exposures
        FROM analytics.fact_experiment_assignment
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        SELECT
            COUNT(*)::bigint,
            COUNT(DISTINCT experiment_assignment_key)::bigint,

            COUNT(*) FILTER (
                WHERE is_exposed
            )::bigint
        INTO
            v_rpt_experiment_rows,
            v_rpt_experiment_unique,
            v_rpt_experiment_exposures
        FROM reporting.vw_experiment_assignment_outcomes
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        SELECT
            COALESCE(SUM(assigned_user_count), 0)::bigint,
            COALESCE(SUM(exposed_user_count), 0)::bigint
        INTO
            v_summary_assignments,
            v_summary_exposures
        FROM reporting.vw_experiment_variant_summary
        WHERE analytics_build_run_id =
              p_analytics_build_run_id;


        -- ----------------------------------------------------
        -- Rate bounds
        -- ----------------------------------------------------

        SELECT COALESCE(SUM(violation_count), 0)::bigint
        INTO v_rate_violations
        FROM (
            SELECT COUNT(*)::bigint AS violation_count
            FROM reporting.vw_installation_cohort_funnel
            WHERE analytics_build_run_id =
                  p_analytics_build_run_id
              AND install_to_signup_rate IS NOT NULL
              AND (
                  install_to_signup_rate < 0
                  OR install_to_signup_rate > 1
              )

            UNION ALL

            SELECT COUNT(*)::bigint
            FROM reporting.vw_signup_cohort_funnel
            WHERE analytics_build_run_id =
                  p_analytics_build_run_id
              AND (
                  (
                      onboarding_start_rate IS NOT NULL
                      AND (
                          onboarding_start_rate < 0
                          OR onboarding_start_rate > 1
                      )
                  )
                  OR
                  (
                      onboarding_completion_rate IS NOT NULL
                      AND (
                          onboarding_completion_rate < 0
                          OR onboarding_completion_rate > 1
                      )
                  )
              )

            UNION ALL

            SELECT COUNT(*)::bigint
            FROM reporting.vw_weekly_acquisition_performance
            WHERE analytics_build_run_id =
                  p_analytics_build_run_id
              AND click_through_rate IS NOT NULL
              AND (
                  click_through_rate < 0
                  OR click_through_rate > 1
              )

            UNION ALL

            SELECT COUNT(*)::bigint
            FROM reporting.vw_trial_conversion_cohorts
            WHERE analytics_build_run_id =
                  p_analytics_build_run_id
              AND trial_to_paid_conversion_rate IS NOT NULL
              AND (
                  trial_to_paid_conversion_rate < 0
                  OR trial_to_paid_conversion_rate > 1
              )

            UNION ALL

            SELECT COUNT(*)::bigint
            FROM reporting.vw_paid_retention_cohorts
            WHERE analytics_build_run_id =
                  p_analytics_build_run_id
              AND (
                  (
                      paid_retention_d30 IS NOT NULL
                      AND (
                          paid_retention_d30 < 0
                          OR paid_retention_d30 > 1
                      )
                  )
                  OR
                  (
                      paid_retention_d90 IS NOT NULL
                      AND (
                          paid_retention_d90 < 0
                          OR paid_retention_d90 > 1
                      )
                  )
                  OR
                  (
                      paid_retention_d180 IS NOT NULL
                      AND (
                          paid_retention_d180 < 0
                          OR paid_retention_d180 > 1
                      )
                  )
                  OR
                  (
                      paid_retention_d365 IS NOT NULL
                      AND (
                          paid_retention_d365 < 0
                          OR paid_retention_d365 > 1
                      )
                  )
              )

            UNION ALL

            SELECT COUNT(*)::bigint
            FROM reporting.vw_daily_subscription_revenue
            WHERE analytics_build_run_id =
                  p_analytics_build_run_id
              AND (
                  (
                      payment_failure_rate IS NOT NULL
                      AND (
                          payment_failure_rate < 0
                          OR payment_failure_rate > 1
                      )
                  )
                  OR
                  (
                      renewal_success_rate IS NOT NULL
                      AND (
                          renewal_success_rate < 0
                          OR renewal_success_rate > 1
                      )
                  )
              )

            UNION ALL

            SELECT COUNT(*)::bigint
            FROM reporting.vw_experiment_variant_summary
            WHERE analytics_build_run_id =
                  p_analytics_build_run_id
              AND (
                  exposure_rate < 0
                  OR exposure_rate > 1
                  OR onboarding_completion_48h_rate < 0
                  OR onboarding_completion_48h_rate > 1
                  OR overall_feature_use_7d_rate < 0
                  OR overall_feature_use_7d_rate > 1
                  OR trial_start_conversion_7d < 0
                  OR trial_start_conversion_7d > 1
                  OR paid_conversion_14d < 0
                  OR paid_conversion_14d > 1
                  OR cancellation_or_expiry_30d_rate < 0
                  OR cancellation_or_expiry_30d_rate > 1
              )
        ) rate_checks;


        -- ----------------------------------------------------
        -- Retention maturity consistency
        -- ----------------------------------------------------

        SELECT COUNT(*)::bigint
        INTO v_retention_violations
        FROM reporting.vw_paid_subscription_retention_base
        WHERE analytics_build_run_id =
              p_analytics_build_run_id
          AND (
              (retained_d30 AND NOT eligible_d30)
              OR
              (retained_d90 AND NOT eligible_d90)
              OR
              (retained_d180 AND NOT eligible_d180)
              OR
              (retained_d365 AND NOT eligible_d365)
          );


        -- ====================================================
        -- PERSIST 31 CHECKS
        -- ====================================================

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'build_control',
            'analytics_build_succeeded',
            v_build_status = 'succeeded',
            CASE WHEN v_build_status = 'succeeded' THEN 0 ELSE 1 END,
            v_build_status,
            'succeeded',
            'Reporting validation may run only against a successful analytics build.'
        );


        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'metric_contract',
            'metric_definition_count',
            v_metric_total = 39,
            CASE WHEN v_metric_total = 39 THEN 0 ELSE 1 END,
            v_metric_total::text,
            '39',
            'Canonical Step 6 metric contract count.'
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'metric_contract',
            'supported_metric_count',
            v_metric_supported = 30,
            CASE WHEN v_metric_supported = 30 THEN 0 ELSE 1 END,
            v_metric_supported::text,
            '30',
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'metric_contract',
            'deferred_metric_count',
            v_metric_deferred = 5,
            CASE WHEN v_metric_deferred = 5 THEN 0 ELSE 1 END,
            v_metric_deferred::text,
            '5',
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'metric_contract',
            'unsupported_metric_count',
            v_metric_unsupported = 4,
            CASE WHEN v_metric_unsupported = 4 THEN 0 ELSE 1 END,
            v_metric_unsupported::text,
            '4',
            NULL
        );


        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'grain',
            'installation_lifecycle_row_count',
            v_lifecycle_rows = v_source_installations,
            CASE WHEN v_lifecycle_rows = v_source_installations THEN 0 ELSE 1 END,
            v_lifecycle_rows::text,
            v_source_installations::text,
            'One reporting lifecycle row per analytics installation.'
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'grain',
            'installation_lifecycle_unique_grain',
            v_lifecycle_rows = v_lifecycle_unique,
            CASE WHEN v_lifecycle_rows = v_lifecycle_unique THEN 0 ELSE 1 END,
            v_lifecycle_unique::text,
            v_lifecycle_rows::text,
            'installation_key must remain unique at lifecycle grain.'
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'grain',
            'daily_product_date_grain',
            v_daily_product_rows = v_dim_date_rows,
            CASE WHEN v_daily_product_rows = v_dim_date_rows THEN 0 ELSE 1 END,
            v_daily_product_rows::text,
            v_dim_date_rows::text,
            'One daily product row per date for the analytics build.'
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'grain',
            'daily_revenue_date_grain',
            v_daily_revenue_rows = v_dim_date_rows,
            CASE WHEN v_daily_revenue_rows = v_dim_date_rows THEN 0 ELSE 1 END,
            v_daily_revenue_rows::text,
            v_dim_date_rows::text,
            'One daily revenue row per date for the analytics build.'
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'grain',
            'experiment_assignment_outcome_unique_grain',
            v_rpt_experiment_rows = v_rpt_experiment_unique,
            CASE WHEN v_rpt_experiment_rows = v_rpt_experiment_unique THEN 0 ELSE 1 END,
            v_rpt_experiment_unique::text,
            v_rpt_experiment_rows::text,
            'One experiment outcome row per experiment assignment.'
        );


        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'product_installations_reconcile',
            v_rpt_installations = v_source_installations,
            CASE WHEN v_rpt_installations = v_source_installations THEN 0 ELSE 1 END,
            v_rpt_installations::text,
            v_source_installations::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'product_signups_reconcile',
            v_rpt_signups = v_source_signups,
            CASE WHEN v_rpt_signups = v_source_signups THEN 0 ELSE 1 END,
            v_rpt_signups::text,
            v_source_signups::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'product_onboarding_started_reconcile',
            v_rpt_onboarding_started = v_source_onboarding_started,
            CASE WHEN v_rpt_onboarding_started = v_source_onboarding_started THEN 0 ELSE 1 END,
            v_rpt_onboarding_started::text,
            v_source_onboarding_started::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'product_onboarding_completed_reconcile',
            v_rpt_onboarding_completed = v_source_onboarding_completed,
            CASE WHEN v_rpt_onboarding_completed = v_source_onboarding_completed THEN 0 ELSE 1 END,
            v_rpt_onboarding_completed::text,
            v_source_onboarding_completed::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'payment_attempts_reconcile',
            v_rpt_payment_attempts = v_source_payment_attempts,
            CASE WHEN v_rpt_payment_attempts = v_source_payment_attempts THEN 0 ELSE 1 END,
            v_rpt_payment_attempts::text,
            v_source_payment_attempts::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'successful_payments_reconcile',
            v_rpt_payment_successes = v_source_payment_successes,
            CASE WHEN v_rpt_payment_successes = v_source_payment_successes THEN 0 ELSE 1 END,
            v_rpt_payment_successes::text,
            v_source_payment_successes::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'failed_payments_reconcile',
            v_rpt_payment_failures = v_source_payment_failures,
            CASE WHEN v_rpt_payment_failures = v_source_payment_failures THEN 0 ELSE 1 END,
            v_rpt_payment_failures::text,
            v_source_payment_failures::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'successful_payment_revenue_reconcile',
            v_rpt_success_revenue = v_source_success_revenue,
            CASE WHEN v_rpt_success_revenue = v_source_success_revenue THEN 0 ELSE 1 END,
            v_rpt_success_revenue::text,
            v_source_success_revenue::text,
            'Successful payment revenue must reconcile exactly to analytics transactions.'
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'marketing_row_count_reconcile',
            v_rpt_marketing_rows = v_source_marketing_rows,
            CASE WHEN v_rpt_marketing_rows = v_source_marketing_rows THEN 0 ELSE 1 END,
            v_rpt_marketing_rows::text,
            v_source_marketing_rows::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'marketing_spend_reconcile',
            v_rpt_marketing_spend = v_source_marketing_spend,
            CASE WHEN v_rpt_marketing_spend = v_source_marketing_spend THEN 0 ELSE 1 END,
            v_rpt_marketing_spend::text,
            v_source_marketing_spend::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'acquisition_installations_reconcile',
            v_rpt_acquisition_installs = v_source_installations,
            CASE WHEN v_rpt_acquisition_installs = v_source_installations THEN 0 ELSE 1 END,
            v_rpt_acquisition_installs::text,
            v_source_installations::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'acquisition_signups_reconcile',
            v_rpt_acquisition_signups = v_source_signups,
            CASE WHEN v_rpt_acquisition_signups = v_source_signups THEN 0 ELSE 1 END,
            v_rpt_acquisition_signups::text,
            v_source_signups::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'feature_events_reconcile',
            (
                SELECT COALESCE(
                    SUM(feature_use_event_count),
                    0
                )::bigint
                FROM reporting.vw_daily_feature_engagement
                WHERE analytics_build_run_id =
                      p_analytics_build_run_id
            ) = v_source_feature_events,
            CASE
                WHEN (
                    SELECT COALESCE(
                        SUM(feature_use_event_count),
                        0
                    )::bigint
                    FROM reporting.vw_daily_feature_engagement
                    WHERE analytics_build_run_id =
                          p_analytics_build_run_id
                ) = v_source_feature_events
                THEN 0
                ELSE 1
            END,
            (
                SELECT COALESCE(
                    SUM(feature_use_event_count),
                    0
                )::bigint::text
                FROM reporting.vw_daily_feature_engagement
                WHERE analytics_build_run_id =
                      p_analytics_build_run_id
            ),
            v_source_feature_events::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'trial_rows_reconcile',
            v_rpt_trial_rows = v_source_trial_rows,
            CASE WHEN v_rpt_trial_rows = v_source_trial_rows THEN 0 ELSE 1 END,
            v_rpt_trial_rows::text,
            v_source_trial_rows::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'paid_retention_base_reconcile',
            v_rpt_paid_retention_rows = v_source_paid_rows,
            CASE WHEN v_rpt_paid_retention_rows = v_source_paid_rows THEN 0 ELSE 1 END,
            v_rpt_paid_retention_rows::text,
            v_source_paid_rows::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'experiment_outcomes_reconcile',
            v_rpt_experiment_rows = v_source_experiment_rows,
            CASE WHEN v_rpt_experiment_rows = v_source_experiment_rows THEN 0 ELSE 1 END,
            v_rpt_experiment_rows::text,
            v_source_experiment_rows::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'experiment_exposures_reconcile',
            v_rpt_experiment_exposures = v_source_experiment_exposures,
            CASE WHEN v_rpt_experiment_exposures = v_source_experiment_exposures THEN 0 ELSE 1 END,
            v_rpt_experiment_exposures::text,
            v_source_experiment_exposures::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'experiment_summary_assignments_reconcile',
            v_summary_assignments = v_source_experiment_rows,
            CASE WHEN v_summary_assignments = v_source_experiment_rows THEN 0 ELSE 1 END,
            v_summary_assignments::text,
            v_source_experiment_rows::text,
            NULL
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'reconciliation',
            'experiment_summary_exposures_reconcile',
            v_summary_exposures = v_source_experiment_exposures,
            CASE WHEN v_summary_exposures = v_source_experiment_exposures THEN 0 ELSE 1 END,
            v_summary_exposures::text,
            v_source_experiment_exposures::text,
            NULL
        );


        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'quality',
            'reporting_rate_bounds',
            v_rate_violations = 0,
            v_rate_violations,
            v_rate_violations::text,
            '0',
            'Canonical rate fields must remain within the inclusive [0,1] interval.'
        );

        PERFORM validation.record_reporting_validation_result(
            v_run_id,
            'quality',
            'retention_maturity_consistency',
            v_retention_violations = 0,
            v_retention_violations,
            v_retention_violations::text,
            '0',
            'No subscription may be retained at a threshold for which it is not observation-mature.'
        );


        SELECT
            COUNT(*)::integer,

            COUNT(*) FILTER (
                WHERE passed
            )::integer,

            COUNT(*) FILTER (
                WHERE NOT passed
            )::integer,

            COALESCE(
                SUM(violation_count),
                0
            )::bigint
        INTO
            v_completed,
            v_passed,
            v_failed,
            v_total_violations
        FROM validation.reporting_validation_results
        WHERE reporting_validation_run_id =
              v_run_id;


        v_final_status :=
            CASE
                WHEN v_completed = v_expected_check_count
                 AND v_failed = 0
                 AND v_total_violations = 0
                    THEN 'succeeded'
                ELSE 'failed'
            END;


        UPDATE validation.reporting_validation_runs
        SET
            status = v_final_status,
            completed_check_count = v_completed,
            passed_check_count = v_passed,
            failed_check_count = v_failed,
            total_violations = v_total_violations,
            completed_at = clock_timestamp(),
            error_message =
                CASE
                    WHEN v_final_status = 'succeeded'
                        THEN NULL
                    ELSE
                        'One or more reporting validation checks failed.'
                END
        WHERE reporting_validation_run_id =
              v_run_id;


        RETURN QUERY
        SELECT
            r.reporting_validation_run_id,
            r.status,
            false,
            r.expected_check_count,
            r.completed_check_count,
            r.passed_check_count,
            r.failed_check_count,
            r.total_violations,
            r.error_message
        FROM validation.reporting_validation_runs r
        WHERE r.reporting_validation_run_id =
              v_run_id;

        RETURN;


    EXCEPTION
        WHEN OTHERS THEN
            GET STACKED DIAGNOSTICS
                v_error = MESSAGE_TEXT;

            SELECT
                COUNT(*)::integer,
                COUNT(*) FILTER (
                    WHERE passed
                )::integer,
                COUNT(*) FILTER (
                    WHERE NOT passed
                )::integer,
                COALESCE(
                    SUM(violation_count),
                    0
                )::bigint
            INTO
                v_completed,
                v_passed,
                v_failed,
                v_total_violations
            FROM validation.reporting_validation_results
            WHERE reporting_validation_run_id =
                  v_run_id;

            UPDATE validation.reporting_validation_runs
            SET
                status = 'failed',
                completed_check_count = v_completed,
                passed_check_count = v_passed,
                failed_check_count = v_failed,
                total_violations = v_total_violations,
                completed_at = clock_timestamp(),
                error_message = v_error
            WHERE reporting_validation_run_id =
                  v_run_id;

            RETURN QUERY
            SELECT
                r.reporting_validation_run_id,
                r.status,
                false,
                r.expected_check_count,
                r.completed_check_count,
                r.passed_check_count,
                r.failed_check_count,
                r.total_violations,
                r.error_message
            FROM validation.reporting_validation_runs r
            WHERE r.reporting_validation_run_id =
                  v_run_id;

            RETURN;
    END;
END;
$$;


COMMENT ON FUNCTION validation.validate_reporting_build(bigint) IS
    'Runs and persists 31 reporting semantic-layer checks for a successful analytics build. Successful validation is idempotent per analytics build.';